-- ==========================================
-- COMPLETE SYSTEM RESET
-- This script Drops, Re-creates, and Seeds the database.
-- ==========================================

-- 1. DROP EXISTING TABLES (Clean Slate)
DROP TABLE IF EXISTS installations CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- 2. CREATE USERS TABLE
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    referral_code TEXT UNIQUE NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. CREATE INSTALLATIONS TABLE
CREATE TABLE installations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id UUID DEFAULT gen_random_uuid(), -- Legacy support if needed
    install_id TEXT UNIQUE NOT NULL,
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    referral_code TEXT REFERENCES users(referral_code),
    extension_id TEXT,
    mellowtel_opted_in BOOLEAN DEFAULT FALSE,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'uninstalled')),
    uninstalled_at TIMESTAMP WITH TIME ZONE,
    device_fingerprint TEXT,
    last_active TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    installed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. CREATE INDEXES
CREATE INDEX idx_users_referral ON users(referral_code);
CREATE INDEX idx_installations_referral ON installations(referral_code);
CREATE INDEX idx_installations_status ON installations(status);
CREATE INDEX idx_installations_install_id ON installations(install_id);

-- 5. CREATE ADMIN USER
-- Email: mukul@gmail.com, Pass: 1234
INSERT INTO users (email, password_hash, referral_code, is_admin, created_at)
VALUES (
    'mukul@gmail.com', 
    '$2a$10$ESAKATeNcCB7uJ3wJn96f.rH9JqEjcm4jJ38XZNvyfoGtKiGpRuP2', 
    'ADMIN001', 
    TRUE,
    NOW()
);

-- 6. VERIFY
SELECT * FROM users;
